import type { Quest, SkillCategory } from "@campusquest/shared";

type PathDefinition = { name: string; category: SkillCategory; goals: string[]; levels: [string[], string[], string[]] };

const baseSkills: Record<string, PathDefinition> = {
  docker: generic("Docker", "infra", ["Backend Engineer", "Cloud Engineer", "MLOps Engineer"]), systemdesign: generic("System design", "systems", ["Backend Engineer", "Full-stack Engineer"]), pytorch: generic("PyTorch", "ml", ["AI Engineer", "Data Scientist"]), git: generic("Git", "tooling", ["Software Engineer", "Full-stack Engineer"]), sql: generic("SQL", "data", ["Data Scientist", "Analytics Engineer"]), postgres: generic("PostgreSQL", "data", ["Backend Engineer", "Data Engineer"]), pandas: generic("Pandas", "ml", ["Data Scientist", "Analytics Engineer"]), numpy: generic("NumPy", "ml", ["AI Engineer", "Data Scientist"]), java: generic("Java", "language", ["Backend Engineer", "Software Engineer"]), aws: generic("AWS", "infra", ["Cloud Engineer", "MLOps Engineer"]), javascript: generic("JavaScript", "language", ["Full-stack Engineer", "Frontend Engineer"]), react: generic("React", "framework", ["Full-stack Engineer", "Frontend Engineer"]),
  sklearn: { name: "scikit-learn", category: "ml", goals: ["AI Engineer", "Data Scientist"], levels: [["Create a reproducible scikit-learn repository", "Load and inspect a dataset", "Clean data and define preprocessing", "Create a train/test split", "Train and evaluate a baseline model"], ["Build a reusable preprocessing pipeline", "Compare multiple estimators", "Run cross-validation", "Tune hyperparameters", "Write an evaluation report"], ["Build an end-to-end prediction project", "Make training reproducible", "Add model tests", "Document results and limitations", "Write a project README", "Pass the GitHub Actions workflow"]] },
};

/** Twelve specialist paths supporting the new market-facing role goals. */
const marketSkills: Record<string, PathDefinition> = {
  llmapps: detailed("LLM applications", "ml", ["AI Engineer"], ["Create a Python API project with pinned LLM dependencies", "Send a structured prompt and validate its response schema", "Store prompts in version-controlled templates", "Add environment-variable configuration and a .env.example", "Document safe local run instructions"], ["Build a multi-turn chat or extraction workflow", "Add prompt-injection and malformed-output handling", "Implement streaming or retry behaviour", "Write unit tests with a mocked model client", "Publish an architecture and cost trade-off note"], ["Ship a focused LLM product with a real user workflow", "Add structured logging without secrets", "Create a regression prompt suite", "Document privacy, limitations and failure modes", "Write a complete README with demo evidence", "Pass the GitHub Actions workflow"]),
  rag: detailed("Retrieval-augmented generation", "ml", ["AI Engineer", "Data Scientist"], ["Create a repository with a small licensed document corpus", "Chunk documents and persist metadata", "Generate embeddings through a configurable provider", "Implement top-k similarity retrieval", "Write a retrieval notebook or script with example queries"], ["Build an ingestion pipeline with duplicate handling", "Add citations from retrieved chunks to answers", "Compare chunking or retrieval configurations", "Create a small labelled retrieval evaluation set", "Document data provenance and retrieval quality"], ["Deliver an end-to-end cited question-answering application", "Add tests for ingestion, retrieval and citation formatting", "Measure answer faithfulness and retrieval quality", "Provide reproducible indexing and run commands", "Document security, privacy and known limitations", "Pass the GitHub Actions workflow"]),
  aievals: detailed("AI evaluation", "ml", ["AI Engineer", "MLOps Engineer"], ["Define a task-specific evaluation rubric", "Create a versioned JSONL evaluation dataset", "Implement deterministic scoring for at least one metric", "Run a baseline model against the dataset", "Write a baseline results summary"], ["Add judge-model or human-review evaluation with documented controls", "Compare two prompts or models", "Track pass rate, latency and cost", "Add regression thresholds for a critical metric", "Publish an evaluation report with error categories"], ["Build a repeatable evaluation harness for an AI feature", "Run it in CI with mocked or recorded fixtures", "Add a regression dashboard or machine-readable report", "Document evaluator bias and metric limitations", "Include reproduction instructions and result snapshots", "Pass the GitHub Actions workflow"]),
  mlops: detailed("MLOps", "ml", ["MLOps Engineer", "AI Engineer"], ["Create a training project with pinned dependencies", "Track parameters, metrics and model artifacts", "Separate configuration from training code", "Save a reproducible baseline model", "Document the training command and outputs"], ["Build a data-validation or model-validation step", "Add experiment comparison", "Containerise the training service", "Write tests for the training pipeline", "Document model versioning and rollback strategy"], ["Deliver a train-to-serve ML pipeline", "Add CI checks for tests and model validation", "Capture model metrics and lineage in artifacts", "Provide deployment and rollback instructions", "Write a model card with limitations", "Pass the GitHub Actions workflow"]),
  kubernetes: detailed("Kubernetes", "infra", ["Cloud Engineer", "MLOps Engineer", "Site Reliability Engineer"], ["Containerise a small web service", "Write Deployment and Service manifests", "Configure resource requests and limits", "Run the manifests on a local cluster", "Document cluster setup and verification commands"], ["Add ConfigMap and Secret references without committing secrets", "Configure readiness and liveness probes", "Deploy a rolling update", "Add a Helm chart or Kustomize overlay", "Write a troubleshooting runbook"], ["Deploy a production-style multi-service application", "Add namespace, RBAC and network-policy controls", "Add autoscaling and resource monitoring", "Test a failed rollout and rollback", "Document architecture and operational ownership", "Pass the GitHub Actions workflow"]),
  terraform: detailed("Terraform", "infra", ["Cloud Engineer", "MLOps Engineer"], ["Create a Terraform project with a pinned provider", "Declare variables, outputs and a remote-safe example tfvars file", "Provision a small cloud resource or local test resource", "Run terraform fmt and validate", "Document init, plan and destroy safety steps"], ["Split reusable infrastructure into modules", "Add environment-specific variable files", "Use a remote-state design without secrets in git", "Run terraform plan in CI", "Document change-review and state-locking practices"], ["Provision a complete application environment as code", "Add least-privilege IAM and network boundaries", "Add policy or static security checks", "Create a tested rollback/change procedure", "Publish architecture and cost assumptions", "Pass the GitHub Actions workflow"]),
  cicd: detailed("CI/CD", "infra", ["Cloud Engineer", "MLOps Engineer", "Full-stack Engineer"], ["Create a GitHub Actions workflow", "Install dependencies deterministically", "Run linting or type checks", "Run the project test suite", "Document local and CI commands"], ["Add build artifacts or container-image creation", "Cache safe dependency paths", "Add pull-request checks", "Protect secrets through repository variables", "Document failure triage for the workflow"], ["Create a staged build-test-release pipeline", "Add dependency or security scanning", "Publish versioned artifacts", "Add a deployment approval or dry-run stage", "Document release and rollback procedures", "Pass the GitHub Actions workflow"]),
  observability: detailed("Observability", "infra", ["Site Reliability Engineer", "Cloud Engineer", "MLOps Engineer"], ["Instrument a service with structured logs", "Add request latency and error metrics", "Expose a health endpoint", "Create a local dashboard or metrics query", "Document telemetry fields and privacy choices"], ["Define service-level indicators and objectives", "Add distributed tracing across two operations", "Create an actionable alert rule", "Simulate an error and inspect telemetry", "Write an incident triage runbook"], ["Deliver an observable service with dashboards and alerts", "Test alert routing or a failure scenario", "Add error-budget or reliability reporting", "Document on-call ownership and escalation", "Write architecture and operational evidence", "Pass the GitHub Actions workflow"]),
  appsec: detailed("Application security", "practice", ["Cybersecurity Engineer", "Full-stack Engineer"], ["Create a small authenticated API or web application", "Validate request input at every public boundary", "Store credentials only in environment variables", "Add secure dependency configuration", "Write a threat-model note for the application"], ["Implement authorization checks for protected actions", "Add secure error handling and audit-friendly logs", "Run dependency and static security scans", "Add tests for an authorization or injection failure", "Document remediations using OWASP terminology"], ["Ship a hardened application with a security review", "Add automated dependency and code scanning", "Demonstrate remediation of a seeded vulnerability", "Document secrets, access control and incident response", "Write a security-focused README section", "Pass the GitHub Actions workflow"]),
  testautomation: detailed("Test automation", "practice", ["Full-stack Engineer", "Cybersecurity Engineer"], ["Create a testable sample application", "Write unit tests for core logic", "Add deterministic fixtures", "Measure or report test coverage", "Document how to run tests locally"], ["Add API or integration tests", "Add one browser or end-to-end test", "Mock external services reliably", "Test a known failure path", "Document the testing pyramid and trade-offs"], ["Deliver a tested application with quality gates", "Run unit, integration and end-to-end tests in CI", "Publish test reports or artifacts", "Add regression coverage for a real defect", "Write a quality and release checklist", "Pass the GitHub Actions workflow"]),
  dbt: detailed("dbt", "data", ["Analytics Engineer", "Data Scientist"], ["Create a dbt project connected to sample warehouse data", "Build staging and mart models", "Declare sources in YAML", "Add schema tests for key columns", "Document dbt build instructions"], ["Implement incremental or reusable models", "Add relationship and freshness tests", "Create model descriptions and lineage docs", "Add a seed or snapshot where appropriate", "Write a data-quality report"], ["Deliver an analytics project with governed marts", "Run dbt build and tests in CI", "Add exposures or downstream-consumer documentation", "Demonstrate a failed data-quality check", "Publish lineage and ownership guidance", "Pass the GitHub Actions workflow"]),
  dataviz: detailed("Data visualization", "data", ["Analytics Engineer", "Data Scientist"], ["Choose a public dataset and define an audience", "Clean data and document assumptions", "Create three appropriate charts", "Add labels, units and accessible colour choices", "Write a short findings summary"], ["Build an interactive dashboard or notebook", "Add filters and meaningful empty states", "Validate calculations against source data", "Add accessibility and mobile checks", "Write a stakeholder-oriented insight report"], ["Publish an end-to-end decision dashboard", "Add automated tests for transformations or calculations", "Document data refresh and governance", "Include a concise executive findings summary", "Write reproduction and accessibility guidance", "Pass the GitHub Actions workflow"]),
};

export const SKILL_PATH_GOALS: Record<string, string[]> = Object.fromEntries(Object.entries({ ...baseSkills, ...marketSkills }).map(([id, definition]) => [id, definition.goals]));

export function skillPathQuests(): Quest[] {
  return Object.entries({ ...baseSkills, ...marketSkills }).flatMap(([id, definition]) => definition.levels.map((labels, index) => {
    const level = index + 1;
    return { id: `q_${id}_l${level}`, title: `${definition.name}: ${["Foundation", "Applied practice", "Portfolio capstone"][index]}`, summary: `Verified ${["foundation", "applied practice", "portfolio capstone"][index]} milestone for ${definition.name}.`, category: "learn", rarity: level === 1 ? "common" : level === 2 ? "rare" : "legendary", xp: level === 1 ? 60 : level === 2 ? 100 : 160, skillsGained: level === 3 ? [{ id, name: definition.name, category: definition.category }] : [], steps: labels.map((label, stepIndex) => ({ id: `q_${id}_l${level}_s${stepIndex + 1}`, label, done: false, verification: label.includes("GitHub Actions") ? "github_workflow" as const : "github_file" as const, verifiedAt: null, verifiedCommit: null, verificationMessage: null })), estimatedHours: level === 1 ? 4 : level === 2 ? 7 : 12, why: `${definition.name} is a tracked skill gap for ${definition.goals.join(", ")}.`, status: "available", pathSkillId: id, pathLevel: level, prerequisiteQuestId: level === 1 ? null : `q_${id}_l${level - 1}`, repositoryUrl: null };
  }));
}

function detailed(name: string, category: SkillCategory, goals: string[], foundation: string[], applied: string[], capstone: string[]): PathDefinition { return { name, category, goals, levels: [foundation, applied, capstone] }; }
function generic(name: string, category: SkillCategory, goals: string[]): PathDefinition { return detailed(name, category, goals, ["Create a reproducible project repository", `Add a working ${name} implementation`, "Add tests or an evaluation artifact", "Document results and design decisions", "Add a runnable example and README"], ["Extend the implementation for a realistic use case", "Add automated validation", "Measure quality, performance or reliability", "Document technical trade-offs", "Publish a reusable usage example"], ["Build an end-to-end portfolio project", "Add production-oriented quality checks", "Add automated tests", "Document results and limitations", "Write a complete project README", "Pass the GitHub Actions workflow"]); }
